--------------------------------------------------------
--  파일이 생성됨 - 월요일-11월-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "KH0804"."MEMBER" 
   (	"NO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"MEM_NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"ZIP_CODE" VARCHAR2(10 BYTE), 
	"MEM_GRADE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "KH0804"."MEMBER"."NO" IS 'INDEX';
 
   COMMENT ON COLUMN "KH0804"."MEMBER"."ID" IS '회원ID';
 
   COMMENT ON COLUMN "KH0804"."MEMBER"."PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "KH0804"."MEMBER"."MEM_NAME" IS '회원이름';
 
   COMMENT ON COLUMN "KH0804"."MEMBER"."EMAIL" IS '이메일';
 
   COMMENT ON COLUMN "KH0804"."MEMBER"."ADDRESS" IS '주소';
 
   COMMENT ON COLUMN "KH0804"."MEMBER"."ZIP_CODE" IS '우편번호';
 
   COMMENT ON COLUMN "KH0804"."MEMBER"."MEM_GRADE" IS '회원등급';
 
   COMMENT ON TABLE "KH0804"."MEMBER"  IS '회원정보';
REM INSERTING into KH0804.MEMBER
SET DEFINE OFF;
Insert into KH0804.MEMBER (NO,ID,PASSWORD,MEM_NAME,EMAIL,ADDRESS,ZIP_CODE,MEM_GRADE) values (1,'1','1','1','1','1','1',1);
Insert into KH0804.MEMBER (NO,ID,PASSWORD,MEM_NAME,EMAIL,ADDRESS,ZIP_CODE,MEM_GRADE) values (1,'2','2','2','2','2','2',10);
Insert into KH0804.MEMBER (NO,ID,PASSWORD,MEM_NAME,EMAIL,ADDRESS,ZIP_CODE,MEM_GRADE) values (2,'3','2','2','2','2','2',10);
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KH0804"."MEMBER_PK" ON "KH0804"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "KH0804"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("NO" NOT NULL ENABLE);
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("ZIP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "KH0804"."MEMBER" MODIFY ("MEM_GRADE" NOT NULL ENABLE);
